// ignore_for_file: prefer_const_constructors

import 'package:twitter_task/tweets.dart';

var tweets = [
  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Shrey',
    name: 'Shrey Flutter',
    timeAgo: '5m',
    text: 'Hi, This is cool to see you all',
    comments: '243',
    retweets: '23K',
    favourites: '112K', 
  ),
  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Sandeep',
    name: 'SandeepDev',
    timeAgo: '12m',
    text: 'Whats up?',
    comments: '46',
    retweets: '4K',
    favourites: '17K',
  ),
  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Android Dev',
    name: 'AndroidDev',
    timeAgo: '20m',
    text: 'New Android updates',
    comments: '305',
    retweets: '20K',
    favourites: '1M',
  ),
  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Google Play',
    name: 'GooglePlay',
    timeAgo: '21m',
    text:
        'Check out our latest updates',
    comments: '1K',
    retweets: '70K',
    favourites: '2M',
  ),
  Tweet(
    avatar:'assets/userIcon.png',
    username: 'Google',
    name: 'Google',
    timeAgo: '26m',
    text: 'HeyGoogle',
    comments: '10K',
    retweets: '500K',
    favourites: '22M',
  ),

  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Shrey',
    name: 'Shrey Flutter',
    timeAgo: '5m',
    text: 'Hi, This is cool to see you all',
    comments: '243',
    retweets: '23K',
    favourites: '112K', 
  ),
  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Sandeep',
    name: 'SandeepDev',
    timeAgo: '12m',
    text: 'Whats up?',
    comments: '46',
    retweets: '4K',
    favourites: '17K',
  ),
  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Android Dev',
    name: 'AndroidDev',
    timeAgo: '20m',
    text: 'News and announcements for developers from the Android team.',
    comments: '305',
    retweets: '20K',
    favourites: '1M',
  ),
  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Google Play',
    name: 'GooglePlay',
    timeAgo: '21m',
    text:
        'Check out our latest updates',
    comments: '1K',
    retweets: '70K',
    favourites: '2M',
  ),
  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Google',
    name: 'Google',
    timeAgo: '26m',
    text: 'HeyGoogle',
    comments: '10K',
    retweets: '500K',
    favourites: '22M',
  ),

  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Shrey',
    name: 'Shrey Flutter',
    timeAgo: '5m',
    text: 'Hi, This is cool to see you all',
    comments: '243',
    retweets: '23K',
    favourites: '112K', 
  ),
  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Sandeep',
    name: 'SandeepDev',
    timeAgo: '12m',
    text: 'Whats up?',
    comments: '46',
    retweets: '4K',
    favourites: '17K',
  ),
  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Android Dev',
    name: 'AndroidDev',
    timeAgo: '20m',
    text: 'News and announcements for developers from the Android team.',
    comments: '305',
    retweets: '20K',
    favourites: '1M',
  ),
  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Google Play',
    name: 'GooglePlay',
    timeAgo: '21m',
    text:
        'Check out our latest updates',
    comments: '1K',
    retweets: '70K',
    favourites: '2M',
  ),
  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Google',
    name: 'Google',
    timeAgo: '26m',
    text: 'HeyGoogle',
    comments: '10K',
    retweets: '500K',
    favourites: '22M',
  ),

  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Shrey',
    name: 'Shrey Flutter',
    timeAgo: '5m',
    text: 'Hi, This is cool to see you all',
    comments: '243',
    retweets: '23K',
    favourites: '112K', 
  ),
  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Sandeep',
    name: 'SandeepDev',
    timeAgo: '12m',
    text: 'Whats up?',
    comments: '46',
    retweets: '4K',
    favourites: '17K',
  ),
  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Android Dev',
    name: 'AndroidDev',
    timeAgo: '20m',
    text: 'News and announcements for developers from the Android team.',
    comments: '305',
    retweets: '20K',
    favourites: '1M',
  ),
  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Google Play',
    name: 'GooglePlay',
    timeAgo: '21m',
    text:
        'Check out our latest updates',
    comments: '1K',
    retweets: '70K',
    favourites: '2M',
  ),
  Tweet(
    avatar: 'assets/userIcon.png',
    username: 'Google',
    name: 'Google',
    timeAgo: '26m',
    text: 'HeyGoogle',
    comments: '10K',
    retweets: '500K',
    favourites: '22M',
  ),
];